name: VPN
on: workflow_dispatch
jobs:
  system:
    runs-on: ubuntu-latest
    steps:
      - name: Dev Container Build and Run Action
        uses: devcontainers/ci@v0.3.1900000417
      - name: Installing Ngrok ..
        run: sudo curl -sSL "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz" -o ngrok.tgz ; sudo tar -xzvf ngrok.tgz ; sudo rm ngrok.tgz ; sudo mv ngrok /usr/bin
      - name: Configuring Ngrok Token ..
        run: ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
      - name: Running Ngrok ..   
        run: ngrok http --domain=${{secrets.NGROK_DOMAIN}} 8080
